default_mode = "sdl_gpu"
min_scale = 0.5
max_scale = 3.0
# 修饰键: left_alt | right_alt | left_ctrl | right_ctrl | left_shift | right_shift | left_gui | right_gui
mod_key = "left_alt"
# 排序方式: name | created_desc | created_asc | modified_desc | modified_asc
sort = "name"
screenshot_dir = "screenshots"

[animation]
image_switch = true

[shaders]
dir = "shaders"

[models]
dir = "models"

[models.birefnet]
standard_model = "BiRefNet.onnx"
lite_model = "BiRefNet_lite.onnx"
used_variant = "lite"

[models.magic_touch]
model = "magic_touch.onnx"
