default_mode = "sdl_gpu"
min_scale = 0.5
max_scale = 3.0
mod_key = "left_ctrl"
screenshot_dir = "screenshots"
shader_dir = "shaders"

[animation]
image_switch = true

[models]
dir = "models"

[models.birefnet]
standard_model = "BiRefNet.onnx"
lite_model = "BiRefNet_lite.onnx"
used_variant = "lite"

[models.magic_touch]
model = "magic_touch.onnx"
