pub const Error = error{
    SdlInitFailed,
    SdlShaderCrossInitFailed,
    SdlTTFInitFailed,
    SdlTextEngineInitFailed,
    SdlCreateGPUDeviceFailed,
    SdlClaimWindowForGPUDeviceFailed,
    SdlGPUTextureCreateFailed,
    SdlGPUFenceWaitFailed,
    SdlCompileShaderFailed,
    SdlCreateGPUGraphicsPipelineFailed,
    SdlSetTextureBlendModeFailed,
    SdlUpdateTextureFailed,
    OutOfMemory,
};
